services:
  - type: web
    name: SIGMA-MD
    env: node
    branch: main
    repo: https://github.com/j98fn4mf9/SIGMA-MD.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        value: 07_02_2024_SIGMA_MD_uK1ki8vw_MAHER_ZUBAIR
      - key: BOT_INFO
        value: inrl;bot;https://i.imgur.com/VIpl3q5.mp4
      - key: WARN_COUNT
        value: 3
      - key: STATUS_VIEW
        value: false
      - key: SAVE_STATUES
        value: true
      - key: STICKER_DATA
        value: INRL;MD
      - key: PREFIX
        value: [!,/.]
      - key: WORK_TYPE
        value: private
      - key: CHATBOT
        value: false
      - key: REACT
        value: command
      - key: AUDIO_DATA
        value: inrl;bot;https://i.imgur.com/VgxJeCm.jpeg
      - key: SUDO
        value: 917025673121
      - key: DATABASE_URL
        value: mongodb+srv://mk:mk@new.vxtfxii.mongodb.net/?retryWrites=true&w=majority
