FROM quay.io/suhailtechinfo/suhail-v2
RUN git clone https://github.com/j98fn4mf9/SIGMA-MD /root/j98fn4mf9/SIGMA-MD
WORKDIR /root/j98fn4mf9/SIGMA-MD/
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]
 
 
